### ISSUE TITLE
App crashing after login

### ISSUE THREAD

**Issue by xdk78** [NyaaPantsu/NyaaPantsu-android-app#49]
After login app crashing, maybe problem is related in api

**Comment by akuma06** [comment]
Yes it is. Will look into it

**Comment by xdk78** [comment]
Streaming too

**Comment by akuma06** [comment]
Streaming works for me though. What errors do you get?

**Comment by xdk78** [comment]
After click, I can see blank activity. I think we need to add new flag to intent like this 
```
intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
```

**Comment by akuma06** [comment]
Might be. I just fixed the api issue.

**Comment by xdk78** [comment]
Streaming still don't working and download too

**Comment by akuma06** [comment]
Streaming works on my end. Download works too, however some files can't be downloaded (if uploaded by magnet). They are generated in a batch every x hours. Try to download latest torrent MAshira and it works

**Comment by xdk78** [comment]
I dunno still don't works. I tried many torrents (yes, i have internet and all permissions for app - Android 6.0) I will try again in a few hours

**Comment by akuma06** [comment]
Try this one https://nyaa.pantsu.cat/view/959749
Actually better is to try on the website if you can download it and then try on the app.

**Comment by xdk78** [comment]
Website
 - working

App
- don't working

http://imgur.com/gOMrp5m

**Comment by akuma06** [comment]
Yeah weird. Do you have an error logged in logcat?

**Comment by xdk78** [comment]
logcat only shows me
`I/Process: Sending signal. PID: 28681 SIG: 9`

**Comment by akuma06** [comment]
Maybe try to make clean build it?

**Comment by ltype** [comment]
Seems no allow permission?

**Comment by xdk78** [comment]
@ltype https://github.com/NyaaPantsu/NyaaPantsu-android-app/issues/49#issuecomment-317189419
Maybe app not detecting permisson (I have Android 6.0), but before works

**Comment by ltype** [comment]
Uninstall app and try again?

**Comment by akuma06** [comment]
I'm on android 7.0 here if it can help

**Comment by xdk78** [comment]
Now working - I just cleaned and rebuild project 2nd time 😄
